### ISSUE TITLE
vimproc_cygwin.dll is not found - Windows 7 32-bits

### ISSUE THREAD

**Issue by TheLox95** [Shougo/vimproc.vim#255]
Hello! I have troubles making this works. I followed the instructions in the readme files and compiled with the `$ mingw32-make -f make_mingw32.mak` command it generates the `vimproc_win32.dll` inside the `lib/` directory but when I run vim from **gitbash** it show this...
![vimprocissue](https://cloud.githubusercontent.com/assets/17032250/15941360/8da6472a-2e49-11e6-81f5-db2bf30fed04.png)
Sorry I'm new with vim. Why is this? How do I solve?

**Comment by Shougo** [comment]
`make -f make_cygwin.mak`
Your environment is Cygwin instead of MinGW32.

**Comment by k-takata** [comment]
The vim.exe comes with "Git for Windows" is a MSYS2 application, not a normal Win32 application.
Currently vimproc considers MSYS2 as Cygwin, because MSYS2 is a fork of Cygwin, so `vimproc_cygwin.dll` is needed.
Maybe you need "[Git for Windows SDK](https://git-for-windows.github.io/#contribute)" or MSYS2 to build `vimproc_cygwin.dll`.
